version: '3.1'
services:
  app:
    container_name: app
    image: node:14
    build: ./
    ports:
      - "3333:3333"
    networks: 
        - webnet
    depends_on:
      database:
        condition: service_healthy
    links:
      - database

  database:
    image: mysql:5.7.22
    container_name: database
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: "exit 0"
    networks: 
      - webnet
    environment:
      - MYSQL_ROOT_PASSWORD=mutant123
      - MYSQL_DATABASE=desafio_mutant
networks:
    webnet: